name: manage-azure-policy-08dcf7e2
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Enforce_Storage_Account_Secure_Transfer_0cdedaec-6eac-4fde-93fa-8f08bb2a7196/**'
#      - .github/workflows/manage-azure-policy-08dcf7e2.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_08dcf7e2}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Enforce_Storage_Account_Secure_Transfer_0cdedaec-6eac-4fde-93fa-8f08bb2a7196/**
